"""Исправление типа полей IP

Revision ID: d0f74bdd8282
Revises: aea607bcf298
Create Date: 2026-06-22 19:46:22.224143

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d0f74bdd8282"
down_revision: Union[str, Sequence[str], None] = "aea607bcf298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tmp")
    op.drop_table("tmp_moved")
    op.drop_table("tmp_mail")
    op.drop_table("fired")
    op.drop_table("mailbox")
    op.alter_column(
        "computers",
        "ip",
        existing_type=mysql.TINYBLOB(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "servers",
        "ip",
        existing_type=mysql.TINYBLOB(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "servers",
        "ip",
        existing_type=sa.Integer(),
        type_=mysql.TINYBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "computers",
        "ip",
        existing_type=sa.Integer(),
        type_=mysql.TINYBLOB(),
        existing_nullable=False,
    )
    op.create_table(
        "mailbox",
        sa.Column("username", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("maildir", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("quota", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("domain", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created", mysql.DATETIME(), nullable=True),
        sa.Column("modified", mysql.DATETIME(), nullable=True),
        sa.Column(
            "active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("crypt_password", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("username"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "fired",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sname", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "tmp_mail",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ip", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("mail", mysql.VARCHAR(length=150), nullable=True),
        sa.Column("password", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("ip1", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fio", mysql.VARCHAR(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "tmp_moved",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "tmp",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ip", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("mac", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("user", mysql.VARCHAR(length=150), nullable=True),
        sa.Column("id_div", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("build", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("room", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("room_switch", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("admin", mysql.VARCHAR(length=150), nullable=True),
        sa.Column("chief", mysql.VARCHAR(length=150), nullable=True),
        sa.Column("os", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
