"""Исправления типов

Revision ID: 9395ee8014dd
Revises: 69c34c2df12e
Create Date: 2026-06-10 22:31:58.373942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9395ee8014dd'
down_revision: Union[str, Sequence[str], None] = '69c34c2df12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('os_id', sa.Integer(), nullable=True))
    op.alter_column('computers', 'ip',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=False)
    op.alter_column('computers', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('computers', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('computers', 'chief_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('computers_ibfk_4'), 'computers', type_='foreignkey')
    op.create_foreign_key(None, 'computers', 'os', ['os_id'], ['id'])
    op.drop_column('computers', 'os')
    op.alter_column('servers', 'ip',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('vlandiv_ibfk_2'), 'vlandiv', type_='foreignkey')
    op.drop_constraint(op.f('vlandiv_ibfk_1'), 'vlandiv', type_='foreignkey')
    op.create_foreign_key(None, 'vlandiv', 'vlans', ['vlan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vlandiv', 'divisions', ['division_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vlans', 'acl',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vlans', 'acl',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'vlandiv', type_='foreignkey')
    op.drop_constraint(None, 'vlandiv', type_='foreignkey')
    op.create_foreign_key(op.f('vlandiv_ibfk_1'), 'vlandiv', 'divisions', ['division_id'], ['id'])
    op.create_foreign_key(op.f('vlandiv_ibfk_2'), 'vlandiv', 'vlans', ['vlan_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('servers', 'ip',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.add_column('computers', sa.Column('os', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.create_foreign_key(op.f('computers_ibfk_4'), 'computers', 'os', ['os'], ['id'])
    op.alter_column('computers', 'chief_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('computers', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('computers', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('computers', 'ip',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_column('computers', 'os_id')
    # ### end Alembic commands ###
