"""Убраны вендоры и FK компьютеров для админа и руководителя

Revision ID: aea607bcf298
Revises: 9395ee8014dd
Create Date: 2026-06-11 20:31:59.914562

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "aea607bcf298"
down_revision: Union[str, Sequence[str], None] = "9395ee8014dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vendors")
    op.alter_column(
        "computers",
        "ip",
        existing_type=mysql.TINYBLOB(),
        type_=sa.LargeBinary(length=16),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("computers_ibfk_1"), "computers", type_="foreignkey")
    op.drop_constraint(op.f("computers_ibfk_2"), "computers", type_="foreignkey")
    op.drop_column("computers", "admin_id")
    op.drop_column("computers", "chief_id")
    op.alter_column(
        "servers",
        "ip",
        existing_type=mysql.TINYBLOB(),
        type_=sa.LargeBinary(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "vlans", "acl", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vlans", "acl", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "servers",
        "ip",
        existing_type=sa.LargeBinary(length=16),
        type_=mysql.TINYBLOB(),
        existing_nullable=False,
    )
    op.add_column(
        "computers",
        sa.Column("chief_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "computers",
        sa.Column("admin_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("computers_ibfk_2"), "computers", "users", ["chief_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("computers_ibfk_1"), "computers", "users", ["admin_id"], ["id"]
    )
    op.alter_column(
        "computers",
        "ip",
        existing_type=sa.LargeBinary(length=16),
        type_=mysql.TINYBLOB(),
        existing_nullable=False,
    )
    op.create_table(
        "vendors",
        sa.Column("mac", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("vendor", mysql.VARCHAR(length=250), nullable=False),
        sa.PrimaryKeyConstraint("mac"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
