"""Инициализация моделей

Revision ID: 69c34c2df12e
Revises: 
Create Date: 2026-06-08 14:42:05.161061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c34c2df12e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stc', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fired',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maildir', sa.String(length=255), nullable=False),
    sa.Column('quota', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('crypt_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tmp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('mac', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('id_div', sa.Integer(), nullable=True),
    sa.Column('build', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('room_switch', sa.String(length=50), nullable=True),
    sa.Column('admin', sa.String(length=150), nullable=True),
    sa.Column('chief', sa.String(length=150), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmp_mail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('ip1', sa.Integer(), nullable=True),
    sa.Column('fio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmp_moved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('mac', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acl', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('domain_login', sa.String(length=100), nullable=False),
    sa.Column('domain_password', sa.String(length=255), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vlandiv',
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ),
    sa.PrimaryKeyConstraint('vlan_id', 'division_id')
    )
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.LargeBinary(length=16), nullable=False),
    sa.Column('mac', sa.String(length=50), nullable=True),
    sa.Column('build', sa.String(length=255), nullable=True),
    sa.Column('pc_room', sa.String(length=255), nullable=True),
    sa.Column('switch_room', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('access_1c', sa.Boolean(), nullable=False),
    sa.Column('access_glx', sa.Boolean(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('chief_id', sa.Integer(), nullable=False),
    sa.Column('os', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chief_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['os'], ['os.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.LargeBinary(length=16), nullable=False),
    sa.Column('mac', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('build', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_disabled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_disabled')
    op.drop_table('servers')
    op.drop_table('computers')
    op.drop_table('vlandiv')
    op.drop_table('users')
    op.drop_table('vlans')
    op.drop_table('vendors')
    op.drop_table('tmp_moved')
    op.drop_table('tmp_mail')
    op.drop_table('tmp')
    op.drop_table('os')
    op.drop_table('mailbox')
    op.drop_table('fired')
    op.drop_table('divisions')
    # ### end Alembic commands ###
